## Really complicated dna differentiation

Imagine a chain of nucleotides, divided in genes and intragenic DNA. Genes must be functioning, so they have a pattern, intragenic DNA not, so it can be random.

...intagrenic----gene----intragenic---gene---intragenic....

GENES

We have N genes Genes have the same order among neanderthal and humans:

Hair--Height--Eyes--Beard.. <- Neanderthal Hair--Height--Eyes--Beard.. <- Human

Humans and neanderthal are similar, so they have similar genes. Hence for a sigle gene i decided to have different variants, like brown hair, blond hairs, but they have to differ for small variation otherwise you would be bald.

From a logic point of view, change a small number of nucleotides from a random sequence so you have the variants, but they keep the same lenght in all the variants.

Genes have correlations between themselves, decided randomly between a random number of genes. For example Genes 1,8,15 are correlated in humans, correlations between 3 elements-> why? 3 is sampled from a "discrete gaussian", why 1,8,15 choseen random.

INTRAGENIC

We have N+1 intragenic sequence, of variable lenght interposed between genes.

How humans differ from neanderthal??

Intragenic dna different in lenght, for example in a human intragenic dna between genes 1 and 2, contains 100 nucleotides, while in the neanderthal 90. Correlations between different genes. like neanderthal correlates Nose and Beard, while human Height and Fat percentage.

How humans differ from humans and neanderthal from neanderthal?

Same intragenic lenght, but different nucleotides. Different genes variants.


In [3]:
#Manopole
#decide the percentage of geneDNA in a sentence.
pc_genes=0.7

#How many genes?
N_genes= 100

#Choose genes to correlate

#How many?
avg_dimension_of_correlation_clusters=10

b=0.4 #how different are different genes ? max 0.5
fraction_of_mutations_per_gene=0.1#percentage of random mutations in gene variants
variants=4 #how may variants?


N_people= 4000
sentence_length= 3000 #HOW LONG A SENTENCE in letters


word_length=5 #HOW LONG A WORD in letters

#do you want same intragenic location in neanderthals and humans?
same = True

#Sorry i did not implemented different genes..

In [4]:

import numpy as np
import pandas as pd


#Build Genes

genes_nucleotides = (sentence_length*pc_genes) //1 
intragenic_nucleotides= sentence_length - genes_nucleotides

print(genes_nucleotides)
print(intragenic_nucleotides)

#How many intergenic sequences?
N_intragenic=N_genes+1



def split_in_different_leghts_sequence(how_many_nucleotides_for_genes, how_many_sequences):
    N_n=how_many_nucleotides_for_genes
    N_s=how_many_sequences
    seqs=np.zeros(N_s)
    for i in range(len(seqs)-1):
        while(True):
            ls=int(np.random.poisson((N_n/N_s)))
            if ls>1: 
                break
        N_n=N_n-ls
        N_s=N_s-1
        seqs[i]=int(ls)
    seqs[-1]=N_n
    return(seqs)


genes_char=split_in_different_leghts_sequence(genes_nucleotides, N_genes)
intragenic_char_humans=split_in_different_leghts_sequence(intragenic_nucleotides, N_intragenic)
if same == False : 
    intragenic_char_neanderthal=split_in_different_leghts_sequence(intragenic_nucleotides, N_intragenic)
else :
    intragenic_char_neanderthal=intragenic_char_humans


print(sum(intragenic_char_neanderthal))
print(sum(intragenic_char_humans))
print(genes_char)

#Now I have the characterization of all genic and intragenic sequences


2100.0
900.0
900.0
900.0
[29. 21. 19. 27. 31. 22. 11. 20. 19. 15. 18. 19. 18. 20. 20. 18. 14. 23.
 19. 21. 27. 25. 24. 13. 32. 25. 32. 28. 17. 20. 22. 23. 20. 22. 21. 23.
 25. 24. 18. 11. 23. 25. 17. 29. 22. 24. 18. 16. 21. 22. 27. 20. 27. 16.
 19. 23. 28. 16. 16. 14. 10. 21. 14. 12. 22. 20. 19. 16. 34. 18. 16. 19.
 22. 15. 21. 18. 16. 28. 13. 28. 20. 19. 19. 17. 24. 27. 17. 23. 24. 21.
 20. 28. 20. 34. 22. 26. 20. 19. 12. 27.]


In [5]:


def correlate_genes(N_genes,cluster_dim):
    clusters=[]
    genes=[i for i in range((N_genes))]
    while(len(genes) != 0):
        while (True):
            curr_cl= int(np.random.poisson((cluster_dim)))
            if curr_cl <= len(genes) and curr_cl>0: break
            #else: print(curr_cl, len(genes))
        clusters.append(np.random.choice(genes, curr_cl, False))
        for c in clusters[-1]:
            genes.remove(c)
    return((clusters))

corrs_human=correlate_genes(N_genes,avg_dimension_of_correlation_clusters)
corrs_neanderthal=correlate_genes(N_genes,avg_dimension_of_correlation_clusters)
print("Theese are the correlation cluster, dont worry about the NAN it simply means that this cluster is smaller thna the number of columns")       
print("human")
display(pd.DataFrame(corrs_human)) 
print("neandertal")
display(pd.DataFrame(corrs_neanderthal))

#Now i got the genes that are correlated.
#In future we can include different genes correlations between human and neanderthal

Theese are the correlation cluster, dont worry about the NAN it simply means that this cluster is smaller thna the number of columns
human


0   1   2     3     4     5     6     7     8     9    10    11    12  \
0   71  38  44  45.0  96.0  97.0  75.0   NaN   NaN   NaN   NaN   NaN   NaN   
1    8  69  19  80.0  65.0  43.0  79.0  66.0  59.0   NaN   NaN   NaN   NaN   
2    9  25  61   4.0  54.0   7.0  41.0  76.0  74.0   NaN   NaN   NaN   NaN   
3   10  20  55  42.0  93.0  52.0  48.0  73.0  84.0  15.0   NaN   NaN   NaN   
4   35  56  13  22.0  29.0  32.0  88.0   5.0  81.0  98.0  51.0  95.0  36.0   
5   70  78   6  72.0  18.0  94.0  17.0  58.0  47.0  64.0   NaN   NaN   NaN   
6   53  12  37  26.0  31.0   0.0  23.0  92.0   NaN   NaN   NaN   NaN   NaN   
7   24  28  16  77.0  91.0  82.0  90.0   1.0  14.0  49.0  83.0  99.0   NaN   
8   33  63  85  40.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9   87  46  68  67.0  21.0  39.0  11.0  60.0  86.0  62.0   NaN   NaN   NaN   
10   2  50  34   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
11  57   3  27   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

      13    14  
0    NaN   NaN  
1    NaN   NaN  
2    NaN   NaN  
3    NaN   NaN  
4   89.0  30.0  
5    NaN   NaN  
6    NaN   NaN  
7    NaN   NaN  
8    NaN   NaN  
9    NaN   NaN  
10   NaN   NaN  
11   NaN   NaN

neandertal


0   1   2   3   4   5     6     7     8     9    10    11    12    13  \
0  58  69  77  28  41  78   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1  94  72  73  32  34  36  30.0  23.0  49.0   NaN   NaN   NaN   NaN   NaN   
2  80  67  18  43  45  38  70.0   9.0   6.0  51.0  57.0  24.0   NaN   NaN   
3  56  31  26  64  37   3  86.0  16.0  25.0  62.0  52.0   7.0  96.0  44.0   
4   0  60  63  35  29  84  95.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
5  79  65  10  92  17  81   1.0  42.0  99.0   NaN   NaN   NaN   NaN   NaN   
6   4  97  54  87  82  48  15.0  40.0  90.0  53.0  66.0  50.0  13.0  89.0   
7  46   8  74  68  22  93  59.0  55.0  71.0  39.0   NaN   NaN   NaN   NaN   
8  85  27  98  83  88  75  47.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
9  12   5   2  19  33  61  21.0  91.0  76.0  20.0   NaN   NaN   NaN   NaN   

     14    15  
0   NaN   NaN  
1   NaN   NaN  
2   NaN   NaN  
3   NaN   NaN  
4   NaN   NaN  
5   NaN   NaN  
6  11.0  14.0  
7   NaN   NaN  
8   NaN   NaN  
9   NaN   NaN

In [6]:
#Now let's build the genes and their variants.

var=variants-1 # ;) read the code and you'll know why
genes=[]

#Here we build the single gene

for i in range(N_genes):    
    tmp_var=np.random.random(4)*2*b +(0.5-b)
    distr_f_a_gene=tmp_var/sum(tmp_var)
    #print(np.cumsum(distr_f_a_gene))
    genes_tmp=[]
    for j in range(int(genes_char[i])): 
        MC_1=np.random.random(1)
        which_nucleotide=0
        for lim in np.cumsum(distr_f_a_gene):
            if(MC_1<=lim): 
                genes_tmp.append(which_nucleotide)
                MC_1= 0
                break
            else:   which_nucleotide+=1 
    genes.append(genes_tmp)
#now add random mutations to characterize each variant.
#we'll have genes->n variants
genes_nv=genes
genes=[]
#print(genes[0][0])

i=0
for gene in genes_nv:
    tmp_var=[]
    tmp_var.append(gene)
    for j in range(var) :
        mutations_where=[]
        mutations_where=np.random.choice(range(len(gene)), 
                                    (int(fraction_of_mutations_per_gene*len(gene))) , False)
        #print(range(len(gene)))
        
        tmp_a=list(gene)
        for m_w in mutations_where:
            tmp_a[m_w]=np.random.randint(4)
            
        tmp_var.append(tmp_a)
    genes.append(tmp_var)
        
print("you got these number of variants per gene : ",len(genes[0]))


you got these number of variants per gene :  4


In [7]:


#Make a prob_distr for each correlation cluster, to choose the variants
corr_distr_human=[]
corr_distr_nean=[]
for i in range(len(corrs_human)):
    #print(np.random.rand(prob_xcorr.shape[0]).argsort())
    prob_xcorr= np.random.random((variants,variants))
    #np.random.shuffle(prob_xcorr, axis=1) #np.random.random(var+1)
   
    prob_xcorr=np.cumsum(prob_xcorr, axis=0)/np.sum(prob_xcorr,axis=0)
    corr_distr_human.append(prob_xcorr)
for i in range(len(corrs_neanderthal)):
    prob_xcorr= np.random.random((variants,variants))
    #print(prob_xcorr)
    prob_xcorr=np.cumsum(prob_xcorr, axis=0)/np.sum(prob_xcorr, axis=0)
    print(prob_xcorr)
    corr_distr_nean.append(prob_xcorr)

print("Limits for the Monte Carlo,matrices as many as the clusters, columns as many as the variants, rows as many as the variants")    
print("human")
display(corr_distr_human)
print("nean")
display(corr_distr_nean)

[[0.07596469 0.13976462 0.40151494 0.40536303]
 [0.2412112  0.33606007 0.48144429 0.43657786]
 [0.78634637 0.71374491 0.60228467 0.66641489]
 [1.         1.         1.         1.        ]]
[[0.34199921 0.43192543 0.43918212 0.15563738]
 [0.65374494 0.73713248 0.72277922 0.59781427]
 [0.98933074 0.91487176 0.91907352 0.6049072 ]
 [1.         1.         1.         1.        ]]
[[0.04327732 0.52364077 0.01266824 0.45529154]
 [0.59535855 0.53091516 0.09366998 0.65837482]
 [0.61164403 0.66257642 0.4682903  0.79909541]
 [1.         1.         1.         1.        ]]
[[0.09511649 0.5019994  0.06149604 0.18618819]
 [0.3861344  0.58228108 0.36578834 0.3198758 ]
 [0.63112959 0.99863137 0.74439389 0.59033468]
 [1.         1.         1.         1.        ]]
[[0.02989139 0.58369466 0.14812177 0.04439152]
 [0.45225362 0.68981853 0.53422221 0.20470087]
 [0.62435566 0.7131494  0.53481011 0.43660754]
 [1.         1.         1.         1.        ]]
[[0.28975634 0.0798017  0.30341555 0.14070806]
 [0.4446

[array([[0.48731142, 0.15541343, 0.21045499, 0.52547256],
        [0.61189057, 0.53225471, 0.67700458, 0.73227708],
        [0.6257951 , 0.87510261, 0.85088915, 0.80047242],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.48565799, 0.29680276, 0.27258323, 0.28268924],
        [0.50696586, 0.52507542, 0.34134759, 0.29573073],
        [0.7206306 , 0.73991247, 0.62397651, 0.85580537],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.25487628, 0.11869668, 0.32808348, 0.3031173 ],
        [0.37029746, 0.17765267, 0.6245509 , 0.46634874],
        [0.73989799, 0.57847682, 0.98600851, 0.73141731],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.13444979, 0.22792548, 0.19680254, 0.16344107],
        [0.14194892, 0.47078371, 0.5789359 , 0.24076149],
        [0.53874555, 0.71500853, 0.8369092 , 0.44580457],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.28082645, 0.13596878, 0.2207573 , 0.13278658],
      

nean


[array([[0.07596469, 0.13976462, 0.40151494, 0.40536303],
        [0.2412112 , 0.33606007, 0.48144429, 0.43657786],
        [0.78634637, 0.71374491, 0.60228467, 0.66641489],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.34199921, 0.43192543, 0.43918212, 0.15563738],
        [0.65374494, 0.73713248, 0.72277922, 0.59781427],
        [0.98933074, 0.91487176, 0.91907352, 0.6049072 ],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.04327732, 0.52364077, 0.01266824, 0.45529154],
        [0.59535855, 0.53091516, 0.09366998, 0.65837482],
        [0.61164403, 0.66257642, 0.4682903 , 0.79909541],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.09511649, 0.5019994 , 0.06149604, 0.18618819],
        [0.3861344 , 0.58228108, 0.36578834, 0.3198758 ],
        [0.63112959, 0.99863137, 0.74439389, 0.59033468],
        [1.        , 1.        , 1.        , 1.        ]]),
 array([[0.02989139, 0.58369466, 0.14812177, 0.04439152],
      

In [12]:
from IPython.display import clear_output
import copy
neanderthals=[]
humans=[]

genome_corr_h=[]
genome_corr_n=[]

for person in range(N_people):
    _tmg=np.random.randint(variants)     #a variant random                  
    clear_output(wait="True")
    print("Loading : ",person, "/", N_people )
    #Build genome 
    human_genome_info=np.zeros(N_genes)       
    
    for i in range(len(corr_distr_human)):    #which cluster
        for gene in corrs_human[i]:               #for every gene in the cluster
            which_variants=0           
            MC_2=np.random.random()
            for lim in corr_distr_human[i][:,_tmg]:
                if(MC_2<=lim):                          #use a monte carlo on markov to choose the variant
                    human_genome_info[gene]=which_variants
                    MC_2= 0
                    _tmg=which_variants                 #jump to the other variant distr for the next it.
                    break
                else: which_variants+=1
    _tmg=np.random.randint(variants)
    print(human_genome_info)
    genome_corr_h.append(copy.deepcopy(human_genome_info))  #now i have the genome, i copy that.
    nean_genome_info=np.zeros(N_genes)
    for i in range(len(corr_distr_nean)):                   #same for neanderthal
        for gene in corrs_neanderthal[i]:
            which_variants=0           
            MC_2=np.random.random()
            for lim in corr_distr_nean[i][:,_tmg]:
                if(MC_2<=lim): 
                    nean_genome_info[gene]=which_variants
                    MC_2= 0
                    _tmg=which_variants
                    break
                else: which_variants+=1
    
    print(nean_genome_info)
    print(list(nean_genome_info))
    
    genome_corr_n.append(copy.deepcopy(nean_genome_info))

    #Build genes:

    human_genome=[]
    nean_genome=[]

    for i in range(len(human_genome_info)):
    
        human_genome.append(genes[i][int(human_genome_info[i])]) #put the complete gene in an array .
    for i in range(len(nean_genome_info)):                       #as decided with the monte carlo.
        nean_genome.append(genes[i][int(nean_genome_info[i])])
    human_genome_info=[]
    nean_genome_info=[]

    #build intragenic
    human_intra=[]                                                #build intragenic
    nean_intra=[]
    for i in range(len(intragenic_char_humans)):                  
        human_intra.append(np.random.randint(4,size=int(intragenic_char_humans[i])))

    for i in range(len(intragenic_char_neanderthal)):
        nean_intra.append(np.random.randint(4,size=int(intragenic_char_humans[i])))

    #build genome

    human_DNA= list(human_intra[0])
    nean_DNA= list(nean_intra[0])
    print(human_DNA)
    for i in range(0,N_genes):
        for nuc in human_genome[i]:
            human_DNA.append(nuc)
        for nuc in human_intra[i+1]:
            human_DNA.append(nuc)
        for nuc in nean_genome[i]:
            nean_DNA.append(nuc)
        for nuc in nean_intra[i+1]:
            nean_DNA.append(nuc)
    #to letters

    human_genome=[]
    nean_genome=[]
    nean_intra=[]
    humna_intra=[]

    my_d={0:'A',1:'C',2:'G',3:'T'}
    for i in range(len(human_DNA)):
        human_DNA[i]=my_d[human_DNA[i]]
    for i in range(len(nean_DNA)):
        nean_DNA[i]=my_d[nean_DNA[i]]
    
    humans.append(human_DNA)
    neanderthals.append(nean_DNA)
humans=np.array(humans)
neanderthals=np.array(neanderthals)

print(humans.shape)
print(neanderthals.shape)

#divide in words




h_DNA= np.array(np.split(humans, sentence_length//word_length, axis=1  ))
n_DNA= np.array(np.split(neanderthals, sentence_length//word_length , axis=1 ))

print(h_DNA.shape)
print(n_DNA.shape)

Loading :  3999 / 4000
[2. 3. 1. 3. 0. 2. 1. 2. 0. 2. 3. 1. 0. 3. 1. 2. 3. 2. 2. 0. 3. 2. 2. 1.
 0. 1. 1. 1. 3. 0. 3. 3. 1. 0. 0. 1. 1. 2. 0. 0. 2. 1. 3. 3. 0. 0. 2. 2.
 2. 2. 3. 0. 3. 0. 0. 3. 2. 1. 2. 2. 1. 2. 0. 2. 2. 0. 3. 1. 3. 0. 2. 2.
 0. 3. 3. 0. 3. 1. 3. 2. 0. 2. 2. 0. 3. 2. 3. 1. 1. 2. 0. 0. 2. 3. 3. 0.
 0. 0. 3. 0.]
[0. 1. 2. 0. 1. 3. 3. 2. 1. 0. 3. 3. 3. 2. 2. 3. 2. 1. 3. 2. 1. 2. 1. 0.
 3. 1. 2. 2. 2. 1. 0. 0. 1. 1. 2. 2. 0. 3. 0. 2. 2. 0. 1. 0. 1. 3. 1. 3.
 3. 2. 0. 0. 2. 2. 1. 1. 0. 1. 0. 0. 3. 2. 2. 3. 0. 2. 3. 2. 2. 1. 1. 3.
 1. 0. 3. 1. 0. 3. 2. 2. 2. 1. 3. 2. 1. 2. 2. 1. 2. 1. 0. 0. 1. 3. 0. 0.
 2. 2. 0. 1.]
[0.0, 1.0, 2.0, 0.0, 1.0, 3.0, 3.0, 2.0, 1.0, 0.0, 3.0, 3.0, 3.0, 2.0, 2.0, 3.0, 2.0, 1.0, 3.0, 2.0, 1.0, 2.0, 1.0, 0.0, 3.0, 1.0, 2.0, 2.0, 2.0, 1.0, 0.0, 0.0, 1.0, 1.0, 2.0, 2.0, 0.0, 3.0, 0.0, 2.0, 2.0, 0.0, 1.0, 0.0, 1.0, 3.0, 1.0, 3.0, 3.0, 2.0, 0.0, 0.0, 2.0, 2.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 3.0, 2.0, 2.0, 3.0, 0.0, 2.0, 3.0, 2.0, 2.0, 1.0, 1.0, 3.0, 1.0,

## Check the words frequency for DNA

In [14]:
DNA_length= sentence_length*N_people
#make words strings.
h_DNA = np.array([[''.join(h_DNA[i,j,:]) for i in range(h_DNA.shape[0]) ]for 
                  j in range(h_DNA.shape[1])])
#make words strings.
n_DNA = np.array([[''.join(n_DNA[i,j,:]) for i in range(n_DNA.shape[0]) ]for 
                  j in range(n_DNA.shape[1])])

print(h_DNA.shape)

h_DNA_check= h_DNA.reshape(DNA_length//word_length)
n_DNA_check= n_DNA.reshape(DNA_length//word_length)
display(h_DNA_check)
h_DNA_check1=[]
n_DNA_check1=[]



from collections import Counter
import matplotlib.pyplot as  plt


##HUMAN
print("here")
counts_h=dict(Counter(h_DNA_check).most_common(50))
print("there")
labels_h, values_h = zip(*counts_h.items())

#sort
indsort_h = np.argsort(values_h)[::-1]

#re_arrange
labels_h= np.array(labels_h)[indsort_h]
values_h= np.array(values_h)[indsort_h]
indexes_h = np.arange(len(values_h))
bar_width=0.2
plt.bar(indexes_h, values_h)
plt.xticks(indexes_h+bar_width,labels_h, rotation= 90)
print(len(counts_h))

plt.show()

##NEANDERTHAL
print("here")
counts_n=dict(Counter(n_DNA_check).most_common(50))
print("there")
labels_n, values_n = zip(*counts_n.items())

#sort
indsort_n = np.argsort(values_n)[::-1]

#re_arrange
labels_n= np.array(labels_n)[indsort_n]
values_n= np.array(values_n)[indsort_n]
indexes_n = np.arange(len(values_n))
bar_width=0.2
plt.bar(indexes_n, values_n)
plt.xticks(indexes_n+bar_width,labels_n, rotation= 90)
print(len(counts_n))

plt.show()



IndexError: too many indices for array

## Prepare Data for NN

In [15]:
h_DNA_NN=[' '.join(h_DNA[i,:]) for i in range(h_DNA.shape[0])]
n_DNA_NN=[' '.join(n_DNA[i,:]) for i in range(n_DNA.shape[0])]

DNA_NN = h_DNA_NN+n_DNA_NN
Y = [1]*len(h_DNA_NN)+[0]*len(n_DNA_NN)


from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(DNA_NN)

encoded_docs = tokenizer.texts_to_sequences(DNA_NN)
max_length = max([len(s.split()) for s in DNA_NN])
X = pad_sequences(encoded_docs, maxlen = max_length, padding = 'post')


from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 42, shuffle = True)

print(X_train.shape)
print(len(Y_train))

vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

(6400, 600)
6400
1025


## Let's build an LSTM NN

In [16]:
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint
from keras.optimizers import SGD, Adam, Adadelta, RMSprop
from keras.layers import Conv1D, Dense, MaxPooling1D, Flatten, Dropout
from keras.layers import Embedding, GlobalAveragePooling1D, LSTM, SimpleRNN, GRU
from keras import regularizers

model = Sequential()
model.add(Embedding(vocab_size, 32, input_length = max_length, dropout = 0.2))
#model.add(SimpleRNN(10, dropout = 0.2, recurrent_dropout = 0.2))  #this sucks
model.add(LSTM(10, dropout = 0.2, recurrent_dropout = 0.2))  #totally killing it
#model.add(Conv1D(10, dropout = 0.2, recurrent_dropout = 0.2)) 

model.add(Dense(5,
                kernel_regularizer=regularizers.l2(0.01),
                activity_regularizer=regularizers.l1(0.01)))
model.add(Dense(1, activation = 'sigmoid'))


model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics = ['accuracy'])
checkpoint = ModelCheckpoint("weights.best.hdf5", monitor = 'val_acc', verbose = 1, 
                             save_best_only = True, mode = 'max')
print(model.summary())

/home/edoardospadetto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  if __name__ == '__main__':


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 600, 32)           32800     
_________________________________________________________________
lstm_1 (LSTM)                (None, 10)                1720      
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6         
Total params: 34,581
Trainable params: 34,581
Non-trainable params: 0
_________________________________________________________________
None


In [17]:
epochs = 7
history = model.fit(X_train, Y_train, 
                    epochs = epochs, verbose = 1, validation_split = 0.2, batch_size = 50, shuffle = True, 
                    callbacks = [checkpoint])

/home/edoardospadetto/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 5120 samples, validate on 1280 samples
Epoch 1/7
5120/5120 [==============================] - 68s 13ms/step - loss: 0.7513 - accuracy: 0.4977 - val_loss: 0.7317 - val_accuracy: 0.5008
Epoch 2/7


/home/edoardospadetto/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py:707: RuntimeWarning: Can save best model only with val_acc available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)


5120/5120 [==============================] - 69s 13ms/step - loss: 0.7227 - accuracy: 0.5047 - val_loss: 0.7127 - val_accuracy: 0.4914
Epoch 3/7
 950/5120 [====>.........................] - ETA: 55s - loss: 0.7124 - accuracy: 0.5168

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import itertools

predicted_labels = model.predict(X_test)
cm = confusion_matrix(Y_test, [np.round(i[0]) for i in predicted_labels])
cm = cm.astype('float') / cm.sum(axis = 1)[:, np.newaxis]



plt.imshow(cm, cmap = plt.cm.Blues)
plt.title('Normalized confusion matrix', fontsize = 15)
plt.colorbar()
plt.xlabel('True label', fontsize = 15)
plt.ylabel('Predicted label', fontsize = 15)
for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    plt.text(j, i, format(cm[i, j], '.2f'),
             horizontalalignment = 'center', verticalalignment = 'center', fontsize = 20,
             color='white' if cm[i, j] > 0.5 else 'black')
plt.show()